### ISSUE TITLE
🤔 [ISSUE] - @eazychart-[react]- React unit tests are emitting warning about svg tag not recognized

### ISSUE THREAD

**Issue by marrouchi** [Hexastack/eazychart#50]
### Description

React unit tests are emitting warning about svg tags not recognized by the browser. I believe that it has something to do with JEST that needs to be configured with the "dom" lib.

### Reproduction steps

```bash
1. `cd packages/ez-react`
2. Run `yarn test`
```

### Logs

```bash
PASS  tests/unit/components/shapes/Bar.spec.tsx
  ● Console

    console.error
      Warning: The tag <rect> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
          at rect
          at shapeDatum (/hdd/workspace/eazychart/packages/ez-react/src/components/shapes/Bar.tsx:13:3)
          at Legend (/hdd/workspace/eazychart/packages/ez-react/src/components/addons/legend/LegendProvider.tsx:10:3)
          at Tooltip (/hdd/workspace/eazychart/packages/ez-react/src/components/addons/tooltip/TooltipProvider.tsx:15:3)
          at dimensions (/hdd/workspace/eazychart/packages/ez-react/src/components/Chart.tsx:38:3)

      40 |     act(() => {
      41 |       // 1st render
    > 42 |       wrapper = render(
         |                 ^
      43 |         <Chart
      44 |           {...baseChartProps}
      45 |           scopedSlots={{

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at createElement (node_modules/react-dom/cjs/react-dom.development.js:9027:9)
      at createInstance (node_modules/react-dom/cjs/react-dom.development.js:10192:20)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:19464:28)
      at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22812:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22787:5)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at tests/unit/components/shapes/Bar.spec.tsx:42:17
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at _callee$ (tests/unit/components/shapes/Bar.spec.tsx:40:5)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
      at Generator._invoke (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)

```

**Comment by G0maa** [comment]
I tried to google this issue a bit, [it seems](https://github.com/facebook/react/issues/16135) like svg elements should be inside `<svg>` tags? i.e.:
```html
<svg>
    <path/>
</svg>
```
